name: Merged Pull Request notifier
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop
jobs:
  isMerged:
    name: Merged Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: 🤝 Send telegram message on Pull Request was merged
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Se ha creado la Pull Request: ${{github.event.pull_request.number}}: 
            📦 Repository: ${{ github.repository }}

            Título: ${{github.event.pull_request.title}}
              - URL: ${{github.event.pull_request.html_url}}
